### ISSUE TITLE
Install required packages if necessary 

### ISSUE THREAD

**Issue by Pablo-source** [Pablo-source/housing_pipelines#2]
Add this code below to ensure packages are installed if necessary

If(!require("tidyverse")) install.packages("tidyverse")
If(!require("renv")) install.packages("renv")
If(!require("redxl")) install.packages("redxl")
If(!require("here")) install.packages("here")
If(!require("janitor")) install.packages("janitor")

**Comment by Pablo-tester** [comment]
All good we can proceed with the  pull request

**Comment by Pablo-source** [comment]
Created brand new issue to install required packages
